server:
  port: 8081

spring:
  application:
    name: auth-service #Nombre único al microservicio
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true # La direccion y base de datos "auth_db"
    username: root # credencial del usuario mysql
    password: mysql # password del usuario mysql
    driver-class-name: com.mysql.cj.jdbc.Driver # controlador de spring para hablar con Mysql
  jpa:
    hibernate:
      ddl-auto: update # Crea o actualiza las tablas automaticamente según tus  clases Entity
    show-sql: true #Muestra las consultas SQL en la consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # Indica el moto de base de datos
        format_sql: true #Formatea las consultas para que sean legibles

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true # Descubre otros servicios
    register-with-eureka: true # Se registra en eureka
  instance:
    prefer-ip-address: true # Usa su IP real

jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30 # Clave secreta usada para firmar y verificar tokens JWT
  expiration: 86400000 # Tiempo de expiración del token en milisegundos