spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true # La direccion y base de datos "auth_db"
    username: root # credencial del usuario mysql
    password: mysql # password del usuario mysql
    driver-class-name: com.mysql.cj.jdbc.Driver # controlador de spring para hablar con Mysql
  jpa:
    hibernate:
      ddl-auto: update # Crea o actualiza las tablas automaticamente según tus  clases Entity
    show-sql: true #Muestra las consultas SQL en la consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # Indica el moto de base de datos
        format_sql: true #Formatea las consultas para que sean legibles
  servlet: #Activa el soporte para subida de archivos,como comprobantes de pago
    multipart:
      enabled: true
      max-file-size: 5MB #Cada archivo 5MB
      max-request-size: 10MB #Toda la solicitud 10MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true # Descubre otros servicios
    register-with-eureka: true # Se registra en eureka
  instance:
    prefer-ip-address: true # Usa su IP real

  file: #Define una carpeta local donde se guardarán archivos subidos
    upload-dir: ./uploads/receipts #La carpeta creada dentro del proyecto

server:
  port: 8082
