spring:
  application:
    name: budget-service
  datasource:
    url: jdbc:mysql://localhost:3306/budget_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true # La direccion y base de datos "auth_db"
    username: root # credencial del usuario mysql
    password: mysql # password del usuario mysql
    driver-class-name: com.mysql.cj.jdbc.Driver # controlador de spring para hablar con Mysql
  jpa:
    hibernate:
      ddl-auto: update # Crea o actualiza las tablas automaticamente según tus  clases Entity
    show-sql: true #Muestra las consultas SQL en la consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # Indica el moto de base de datos
        format_sql: true #Formatea las consultas para que sean legibles

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true # Descubre otros servicios
    register-with-eureka: true # Se registra en eureka
  instance:
    prefer-ip-address: true # Usa su IP real

#Configuración de Feign Client
feign:
  client:
    config:
      default:
        connecTimeout: 5000
        readTimeout: 5000

server:
  port: 8083
